openapi: 3.0.0
info:
  title: TherapistTrack
  version: 1.0.0
  description: Documentación de API generada por Swagger
  contact:
    name: Soporte API
servers:
  - url: 'http://localhost:3001'

tags:
  - name: Gestión de usuarios
    description: Gestión de usuarios, incluyendo registro, actualización y eliminación.
  - name: Plantillas de Paciente/Expediente
    description: Gestión de plantillas de paciente y expediente.
  - name: Plantillas de Archivo
    description: Gestión de plantillas de archivos.
  - name: Operaciones de expedientes
    description: Gestión de expedientes, incluyendo creación, actualización y eliminación.
  - name: Operaciones de archivo
    description: Operaciones relacionadas con la gestión de archivos.

paths:
  /users/register:
    $ref: './paths/user_management.yaml#/userRegister'
  /users/update:
    $ref: './paths/user_management.yaml#/userUpdate'
  /users/delete:
    $ref: './paths/user_management.yaml#/userDelete'
  /users/list:
    $ref: './paths/user_management.yaml#/userList'
  /users/@me:
    $ref: './paths/user_management.yaml#/userMe'
  /users/{:id}:
    $ref: './paths/user_management.yaml#/userGetByID'

  /createFile:
    $ref: './paths/file_operations.yaml#/createFile'
  /updateFile:
    $ref: './paths/file_operations.yaml#/updateFile'
  /deleteFile:
    $ref: './paths/file_operations.yaml#/deleteFile'
  /listFiles:
    $ref: './paths/file_operations.yaml#/listFiles'
  /getFileById:
    $ref: './paths/file_operations.yaml#/getFileById'

  /doctor/PatientTemplate:
    $ref: './paths/patient_template.yaml#/doctorPatientTemplate'
  /doctor/PatientTemplate/list:
    $ref: './paths/patient_template.yaml#/doctorPatientTemplateList'
  /doctor/PatientTemplate/fields:
    $ref: './paths/patient_template.yaml#/doctorPatientTemplateFields'
  /doctor/FileTemplate:
    $ref: './paths/doctor_configuration.yaml#/doctorFileTemplate'
  /doctor/FileTemplate/fields:
    $ref: './paths/doctor_configuration.yaml#/doctorFileTemplateFields'

  /records/:
    $ref: './paths/record_operations.yaml#/baseRecordRoute'
  /records/search:
    $ref: './paths/record_operations.yaml#/searchRecords'
