openapi: 3.0.0
info:
  title: TherapistTrack
  version: 1.0.0
  description: Documentación de API generada por Swagger
  contact:
    name: Soporte API
servers:
  - url: 'http://localhost:3001'

tags:
  - name: Gestión de usuarios
    description: Gestión de usuarios, incluyendo registro, actualización y eliminación.
  - name: Configuración de Doctor
    description: Gestión de plantillas de paciente y expediente.
  - name: Operaciones de archivo
    description: Operaciones relacionadas con la gestión de archivos.

paths:
  /users/register:
    $ref: './paths/user_management.yaml#/userRegister'
  /users/update:
    $ref: './paths/user_management.yaml#/userUpdate'
  /users/delete:
    $ref: './paths/user_management.yaml#/userDelete'
  /users/list:
    $ref: './paths/user_management.yaml#/userList'
  /users/@me:
    $ref: './paths/user_management.yaml#/userMe'
  /users/{:id}:
    $ref: './paths/user_management.yaml#/userGetByID'

  /files/create:
    $ref: './paths/file_operations.yaml#/createFile'
  /files/:
    $ref: './paths/file_operations.yaml#/updateFile'
  /files/listFiles:
    $ref: './paths/file_operations.yaml#/listFiles'
  /files/file:
    $ref: './paths/file_operations.yaml#/getFileById'

  /doctor/PatientTemplate:
    $ref: './paths/doctor_configuration.yaml#/doctorPatientTemplate'
  /doctor/PatientTemplate/fields:
    $ref: './paths/doctor_configuration.yaml#/doctorPatientTemplateFields'
  /doctor/FileTemplate:
    $ref: './paths/doctor_configuration.yaml#/doctorFileTemplate'
  /doctor/FileTemplate/fields:
    $ref: './paths/doctor_configuration.yaml#/doctorFileTemplateFields'
