openapi: 3.0.0
info:
  title: TherapistTrack
  version: 1.0.0
  description: Documentación de API generada por Swagger
  contact:
    name: Soporte API
servers:
  - url: 'http://localhost:3001'

tags:
  - name: Autenticación
    description: Operaciones de autenticación como login y registro.
  - name: Gestión de usuarios
    description: Gestión de usuarios, incluyendo registro, actualización y eliminación.
  - name: Operaciones de archivo
    description: Operaciones relacionadas con la gestión de archivos.
  - name: Doctor Configuration
    description: Configuración y gestión específica de doctores, incluyendo plantillas y campos personalizados.

paths:
  /login:
    $ref: './paths/authentication.yaml#/login'
  /user/logout:
    $ref: './paths/authentication.yaml#/userLogout'
  /user/credentials:
    $ref: './paths/authentication.yaml#/userCredentials'
  /user/register:
    $ref: './paths/user_management.yaml#/userRegister'
  /user/delete:
    $ref: './paths/user_management.yaml#/userDelete'
  /user/update:
    $ref: './paths/user_management.yaml#/userUpdate'
  /user/list:
    $ref: './paths/user_management.yaml#/userList'
  /upload:
    $ref: './paths/file_operations.yaml#/upload'
  /pdf/{filename}:
    $ref: './paths/file_operations.yaml#/pdfFilename'
  /doctor/PatientTemplate:
    $ref: './paths/doctor_configuration.yaml#/doctorPatientTemplate'
  /doctor/PatientTemplate/fields:
    $ref: './paths/doctor_configuration.yaml#/doctorPatientTemplateFields'
  /doctor/FileTemplate:
    $ref: './paths/doctor_configuration.yaml#/doctorFileTemplate'
  /doctor/FileTemplate/fields:
    $ref: './paths/doctor_configuration.yaml#/doctorFileTemplateFields'

components:
  schemas:
    UserInfoResponse:
      type: object
      properties:
        username:
          type: string
        name:
          type: string
        lastName:
          type: string
        phones:
          type: array
          items:
            type: string
        role:
          type: string
        mails:
          type: array
          items:
            type: string
        collegiateNumber:
          type: string
        specialty:
          type: string
        startDate:
          type: string
        endDate:
          type: string
        DPI:
          type: string
